from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

path = r"C:\Users\Dell\PycharmProjects\sushmitha\drivers\chromedriver.exe"
driver = webdriver.Chrome(executable_path=path)
driver.implicitly_wait(10)

driver.get(r"https://www.goibibo.com/cars/")
driver.maximize_window()
driver.find_element("xpath", '(//span[@class="CustomRadioButtonUIstyles__Dot-sc-1ffkzia-2 hAzeQw"])[1]').click()
time.sleep(2)
driver.find_element("xpath", '//input[@id="downshift-1-input"]').send_keys('Bangalore')
time.sleep(2)
driver.find_element("xpath", '//div[@id="downshift-1-item-0"]').click()
time.sleep(1)
driver.find_element("xpath", '(//input[@name="autosuggest"])[2]').send_keys('Mysore')
time.sleep(2)
driver.find_element("xpath", '(//li[@class="AutoSuggeststyles__ListItem-sc-1xb3zd-2 kOvBXW"])[1]').click()
time.sleep(1)
driver.find_element("xpath", '(//span[@class="HomeSearchWidgetstyles__DateTxt-sc-1rvppov-7 eiggyI"])[1]').click()
time.sleep(1)
driver.find_element("xpath", '//span[text()="30"]').click()
time.sleep(1)
driver.find_element("xpath", '(//span[@class="HomeSearchWidgetstyles__DateTxt-sc-1rvppov-7 eiggyI"])[2]').click()
time.sleep(1)
driver.find_element("xpath", '//span[text()="05:00 PM"]').click()
time.sleep(1)
driver.find_element("xpath", '//button[text()="SEARCH CABS"]').click()
time.sleep(4)
driver.find_element("xpath", '(//h4[@class="cabName"]/../../../../..//button[@class="Buttonstyles__BookNowBtn-sc-1emdluo-0 gDRSaJ"])[1]').click()
time.sleep(5)
driver.find_element("xpath", '(//input[@class="textInput"])[1]').send_keys("Brookefield mall")
time.sleep(3)
driver.find_element("xpath", '(//p[@class="AutoSuggeststyles__MainTxt-sc-1xb3zd-4 fvzcbc"])[1]').click()
driver.find_element("xpath", '//input[@placeholder="Enter Full Name"]').send_keys("Sushmitha")
time.sleep(2)
driver.find_element("xpath", '//input[@placeholder="Enter Mobile Number"]').send_keys("8861930499")
time.sleep(2)
driver.find_element("xpath", '//input[@placeholder="Enter Email"]').send_keys("sushmithakp321@gmail.com")
time.sleep(2)
driver.find_element("xpath", '(//label[@class="makeFlex spaceBetween"])[1]').click()
time.sleep(2)
driver.find_element("id", 'paymentButton').click()